default:
  stackName: sat-api-v3

  system_bucket: change-me 

  tags:
    project: sat-api

  capabilities:
    - CAPABILITY_IAM

  es:
    name: es6
    version: '6.0'
    instanceCount: 1
    instanceType: t2.small.elasticsearch
    volumeSize: 35 

  apis:
    - name: stac

  tasks:
    SatApiTaskRunner:
      image: developmentseed/lambda-ecs-runner:node-8.11
      cpu: 512
      memory: 1024
      envs:
        stackName: '{{stackName}}'

  lambdas:
    ingest:
      source: 'node_modules/@sat-utils/ingest/dist/'
      handler: index.handler
      timeout: 300
      memory: 1600
      envs:
        bucket: '{{system_bucket}}'
        prefix: '{{stackName}}'
        ES_HOST: "!GetAtt {{es.name}}Domain.DomainEndpoint"
    api:
      source: 'node_modules/@sat-utils/api/dist/'
      handler: index.handler
      timeout: 100
      envs:
        ES_HOST: "!GetAtt {{es.name}}Domain.DomainEndpoint"
      apiGateway:
        - api: stac
          path: '{proxy+}'
          method: get
          cors: true
