default:
  stackName: sat-api-v3

  buckets:
    internal: change-me 

  tags:
    project: sat-api

  capabilities:
    - CAPABILITY_IAM

  es:
    name: es6
    version: '6.0'
    instanceCount: 1
    instanceType: t2.small.elasticsearch
    volumeSize: 80

  apis:
    - name: stac

  lambdas:
    landsat:
      source: 'dist/landsat/'
      handler: index.handler
      timeout: 300
      memory: 1024
      envs:
        ES_HOST: "!GetAtt {{es.name}}Domain.DomainEndpoint"
    sentinel:
      source: 'dist/sentinel/'
      handler: index.handler
      timeout: 300
      memory: 512
      envs:
        ES_HOST: "!GetAtt {{es.name}}Domain.DomainEndpoint"
    ingest:
      source: 'dist/ingest/'
      handler: index.handler
      timeout: 300
      memory: 1024
      envs:
        bucket: '{{buckets.internal}}'
        prefix: '{{stackName}}'
    manager:
      source: 'dist/manager/'
      handler: index.handler
      timeout: 300
      memory: 192
      envs:
        ES_HOST: "!GetAtt {{es.name}}Domain.DomainEndpoint"
        ES_ARN: "!GetAtt {{es.name}}Domain.DomainArn"
        ROLE_ARN: "!GetAtt LambdaRole.Arn"
        BUCKET: "{{buckets.internal}}"
    api:
      source: 'dist/api/'
      handler: index.handler
      timeout: 100
      envs:
        ES_HOST: "!GetAtt {{es.name}}Domain.DomainEndpoint"
      apiGateway:
        - api: stac
          path: '{proxy+}'
          method: get
          cors: true
