version: '2'

services:

  base:
    build:
      context: .
    image: satutils/sat-api:latest
    env_file: .env
    entrypoint: /bin/bash

  test:
    image: satutils/sat-api:latest
    env_file: .env
    entrypoint: yarn test
