default:
  stackName: change-me
  system_bucket: sat-api-us-east-1

  tags:
    project: sat-api

dev:
  stackName: sat-api-dev
  es:
    instanceCount: 2
    instanceType: m3.medium.elasticsearch
    volumeSize: 80

prod:
  stackName: sat-api
  es:
    instanceCount: 2
    instanceType: m3.medium.elasticsearch
    volumeSize: 80
