default:
  stackName: sat-api-v1-dev

  buckets:
    internal: sat-api

  tags:
    project: sat-api

  capabilities:
    - CAPABILITY_IAM

  es:
    name: es6
    version: '6.0'
    instanceCount: 2
    instanceType: m3.medium.elasticsearch
    volumeSize: 80

  apis:
    - name: satellites

  lambdas:
    - name: landsat
      source: 'dist/landsat/'
      handler: index.handler
      timeout: 300
      memory: 1024
      envs:
        ES_INDEX: 'sat-api'
        ES_HOST: "!GetAtt {{es.name}}Domain.DomainEndpoint"
    - name: sentinel
      source: 'dist/sentinel/'
      handler: index.handler
      timeout: 300
      memory: 512
      envs:
        ES_INDEX: 'sat-api'
        ES_HOST: "!GetAtt {{es.name}}Domain.DomainEndpoint"
    - name: split
      source: 'dist/split/'
      handler: index.handler
      timeout: 300
      memory: 1024
      envs:
        bucket: '{{buckets.internal}}'
        prefix: '{{stackName}}'
    - name: manager
      source: 'dist/manager/'
      handler: index.handler
      timeout: 300
      memory: 192
      envs:
        ES_INDEX: 'sat-api'
        ES_HOST: "!GetAtt {{es.name}}Domain.DomainEndpoint"
    - name: api
      source: 'dist/api/'
      handler: index.handler
      timeout: 100
      envs:
        ES_INDEX: 'sat-api'
        ES_HOST: "!GetAtt {{es.name}}Domain.DomainEndpoint"
      apiGateway:
        - api: satellites
          path: 'items'
          method: get
        - api: satellites
          path: 'items'
          method: post
          cors: true
        - api: satellites
          path: 'count'
          method: get
          cors: true

production:
  stackName: sat-api-v1
