version: 2

references:
  restore_repo: &restore_repo
    restore_cache:
      keys:
        - v1-repo-{{ .Branch }}-{{ .Revision }}
        - v1-repo-{{ .Branch }}
        - v1-repo

jobs:
  test:
    docker:
      - image: circleci/node:8.11
    steps:
      - *restore_repo
      - checkout
      - run:
          name: Install
          command: |
            yarn
            yarn bootstrap
      - run:
          name: Lint
          command: yarn eslint
      - run:
          name: Build and test
          command: |
            yarn build
            yarn test
      - run:
          name: Build Documentation
          command: |
            if [[  "$CIRCLE_BRANCH" == 'master' ]]; then
              yarn docs-build
            fi
      - run:
          name: Deploy example to aws
          command: |
            if [[  "$CIRCLE_BRANCH" == 'master' ]]; then
              echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
              VERSION=$(jq --raw-output .version lerna.json)
              node_modules/.bin/lerna publish --skip-git --repo-version $VERSION --yes --force-publish=*
            fi

  docker:
    steps:
      - *restore_repo
      - checkout
      - save_cache:
          key: v1-repo-{{ .Branch }}-{{ .Revision }}
          paths:
            - ~/project
      - run:
          name: Build Docker image
          command: |
            touch .env
            docker-compose build
      - run:
          name: Deploy Docker image
          command: |
            if [[  "$CIRCLE_BRANCH" == 'master' ]]; then
              echo 'test'
              # TODO - update environment variables in lambda
            fi


workflows:
  version: 2
  test:
    jobs:
      - test
  docker_deploy:
    jobs:
      - docker
#          requires:
#            - test
#          filters:
#            branches:
#              only: master
