version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8.11
    working_directory: ~/project
    steps:
      - checkout

      - run:
          name: Install
          command: yarn
      - run:
          name: Bootstrap
          command: yarn bootstrap 
      - run:
          name: Lint
          command: yarn eslint
      - run:
          name: Build 
          command: yarn build 
      - run:
          name: Test
          command: yarn test
    
      - run:
          name: Generate and Deploy Documentation
          command: |
            yarn docs-build

            if [[  "$CIRCLE_BRANCH" == 'master' ]]; then
              cd _book
              git init
              git config user.name "Devseed"
              git config user.email "info@developmentseed.org"
              git add -A
              git commit -m "Automated build in circleci"
              git push --force --quiet git@github.com:sat-utils/sat-api master:gh-pages
              rm -rf .git
            fi