version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8.11
    working_directory: ~/project
    steps:
      - checkout

      - run:
          name: Installing Dependencies
          command: |
            yarn
            yarn bootstrap
            yarn build
      - run:
          name: Run test
          command: yarn test

      # - run:
      #     name: Deploy to staging
      #     command: |
      #       if [ "${CIRCLE_BRANCH}" == "_develop" ]; then
      #         VERSION=$(grep -m1 version package.json | awk -F: '{ print $2 }' | sed 's/[", ]//g')
      #         kes cf deploy -r us-east-1
      #       fi          
      #     no_output_timeout: "30m"

      # - run:
      #     name: Deploy to production
      #     command: |
      #       if [ "${CIRCLE_BRANCH}" == "_master" ]; then
      #         VERSION=$(grep -m1 version package.json | awk -F: '{ print $2 }' | sed 's/[", ]//g')
      #         kes cf deploy -r us-east-1 -d production
      #       fi
      #     no_output_timeout: "30m"
